import { css } from "styled-system/css";

export const CODE_BLOCK_COLLAPSED_HEIGHT = 240;

export const markdownStyles = {
  h1: css({ fontSize: "2xl", fontWeight: "bold", mt: 6, mb: 4 }),
  h2: css({ fontSize: "xl", fontWeight: "semibold", mt: 4, mb: 2 }),
  h3: css({ fontSize: "lg", fontWeight: "medium", mt: 3, mb: 1 }),
  headingTarget: css({
    scrollMarginTop: "96px",
    position: "relative",
    overflow: "visible",
    "& [data-heading-anchor='true']": {
      opacity: 0,
      pointerEvents: "auto",
    },
    "&:hover [data-heading-anchor='true']": {
      opacity: 1,
    },
    "& [data-heading-anchor='true']:hover": {
      opacity: 1,
    },
    "& [data-heading-anchor='true']:focus-visible": {
      opacity: 1,
    },
  }),
  headingAnchor: css({
    position: "absolute",
    left: "-1.1rem",
    top: "50%",
    transform: "translateY(-50%)",
    opacity: 0,
    color: "fg.muted",
    textDecoration: "none",
    fontSize: "0.85em",
    transition: "opacity 120ms ease",
    _hover: { color: "fg.default" },
  }),
  p: css({ fontSize: "md", lineHeight: "relaxed", mb: 3 }),
  a: css({ color: "accent.default", textDecoration: "underline" }),
  ul: css({ listStyleType: "disc", pl: 6, mb: 4 }),
  ol: css({ listStyleType: "decimal", pl: 6, mb: 4 }),
  li: css({ mb: 1 }),
  blockquote: css({
    borderLeftWidth: "4px",
    borderLeftColor: "border.subtle",
    pl: 4,
    py: 1,
    my: 4,
    fontStyle: "italic",
    color: "fg.muted",
  }),
  preWrapper: css({
    position: "relative",
    my: 4,
    borderRadius: "md",
    overflow: "visible",
    "&:hover [data-code-action='true']": {
      opacity: 1,
      pointerEvents: "auto",
      transform: "translate(0, 0)",
    },
    "&:focus-within [data-code-action='true']": {
      opacity: 1,
      pointerEvents: "auto",
      transform: "translate(0, 0)",
    },
  }),
  codeActionTray: css({
    position: "absolute",
    top: 0,
    right: "8px",
    transform: "translate(0, -30%)",
    zIndex: 3,
    display: "inline-flex",
    alignItems: "center",
    gap: "1",
  }),
  pre: css({
    fontFamily: "mono",
    bg: "bg.subtle",
    borderRadius: "md",
    overflow: "auto",
    p: 4,
    m: 0,
  }),
  preCollapsed: css({
    maxHeight: `${CODE_BLOCK_COLLAPSED_HEIGHT}px`,
    overflow: "hidden",
  }),
  copyButton: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "1",
    borderWidth: "1px",
    borderColor: "border.default",
    bg: "bg.default",
    color: "fg.default",
    borderRadius: "sm",
    px: "2",
    py: "1",
    fontSize: "xs",
    cursor: "pointer",
    opacity: 0,
    pointerEvents: "none",
    transition: "opacity 140ms ease, transform 140ms ease",
    _hover: { bg: "bg.subtle" },
  }),
  expandIconButton: css({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: "1px",
    borderColor: "border.default",
    bg: "bg.default",
    color: "fg.default",
    borderRadius: "sm",
    width: "7",
    height: "7",
    cursor: "pointer",
    opacity: 0,
    pointerEvents: "none",
    transition: "opacity 140ms ease, transform 140ms ease",
    _hover: { bg: "bg.subtle" },
  }),
  fadeOverlay: css({
    position: "absolute",
    bottom: "28px",
    left: 0,
    right: 0,
    height: "40px",
    background:
      "linear-gradient(to bottom, transparent 0%, token(colors.bg.subtle) 100%)",
    pointerEvents: "none",
  }),
  expandButton: css({
    width: "100%",
    py: 1.5,
    px: 4,
    bg: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: "xs",
    color: "fg.muted",
    textAlign: "center",
    fontFamily: "sans",
    _hover: {
      color: "fg.default",
      textDecoration: "underline",
    },
  }),
  inlineCode: css({
    fontFamily: "mono",
    bg: "bg.subtle",
    px: 1.5,
    py: 0.5,
    borderRadius: "sm",
    fontSize: "sm",
  }),
  blockCode: css({
    "--md-code-line-digits": "2",
    "--md-code-line-gap": "0.5rem",
    "--md-code-line-column":
      "calc(var(--md-code-line-digits) * 0.72ch + 0.85rem)",
    fontFamily: "mono",
    fontSize: "sm",
    lineHeight: "relaxed",
    display: "block",
    "& .code-line": {
      display: "block",
      paddingLeft: "calc(var(--md-code-line-column) + var(--md-code-line-gap))",
      position: "relative",
      minHeight: "1.4em",
      whiteSpace: "pre",
    },
    "& .code-line::before": {
      content: "attr(data-line)",
      position: "absolute",
      left: 0,
      width: "var(--md-code-line-column)",
      textAlign: "right",
      color: "fg.muted",
      userSelect: "none",
    },
  }),
  mermaid: css({
    my: 0,
    px: 4,
    py: 3,
    bg: "bg.default",
    borderTopWidth: "1px",
    borderTopColor: "border.default",
    overflowX: "auto",
    "& svg": {
      display: "block",
      maxW: "100%",
      h: "auto",
      mx: "auto",
    },
  }),
  mermaidError: css({
    px: 4,
    py: 2,
    color: "red.surface.fg",
    bg: "red.surface.bg",
    borderTopWidth: "1px",
    borderTopColor: "red.surface.border",
    fontSize: "sm",
  }),
  codeDrawerContent: css({
    maxW: { base: "100vw", md: "min(92vw, 88ch)" },
    h: "100dvh",
    borderLeftWidth: "1px",
    borderLeftColor: "border.subtle",
    bg: "bg.default",
  }),
  codeDrawerHeader: css({
    position: "sticky",
    top: 0,
    zIndex: 2,
    pb: 3,
    borderBottomWidth: "1px",
    borderBottomColor: "border.subtle",
    bg: "bg.default",
    backdropFilter: "blur(6px)",
  }),
  codeDrawerHeaderTop: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 3,
  }),
  codeDrawerHeaderActions: css({
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
  }),
  codeDrawerDescription: css({
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontSize: "xs",
    color: "fg.muted",
  }),
  codeDrawerBody: css({
    p: 0,
    bg: "bg.default",
    overflow: "auto",
  }),
  codeDrawerScroll: css({
    h: "calc(100dvh - 110px)",
    w: "100%",
    overflow: "auto",
  }),
  codeDrawerPre: css({
    m: 0,
    px: { base: 4, md: 6 },
    py: { base: 4, md: 5 },
    bg: "gray.2",
    minH: "100%",
    overflow: "visible",
  }),
  mermaidDialogContent: css({
    w: "min(95vw, 1280px)",
    maxW: "95vw",
    h: "min(90dvh, 900px)",
    maxH: "90dvh",
    borderWidth: "1px",
    borderColor: "border.subtle",
    bg: "bg.default",
  }),
  mermaidDialogHeader: css({
    position: "sticky",
    top: 0,
    zIndex: 2,
    pb: 3,
    borderBottomWidth: "1px",
    borderBottomColor: "border.subtle",
    bg: "bg.default",
    backdropFilter: "blur(6px)",
  }),
  mermaidDialogHeaderTop: css({
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 3,
  }),
  mermaidDialogHeaderActions: css({
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  }),
  mermaidDialogDescription: css({
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    fontSize: "xs",
    color: "fg.muted",
  }),
  mermaidDialogBody: css({
    p: 0,
    h: "100%",
  }),
  mermaidDialogViewport: css({
    position: "relative",
    h: "calc(90dvh - 130px)",
    minH: "420px",
    w: "100%",
    overflow: "hidden",
    bg: "bg.default",
    touchAction: "none",
    cursor: "grab",
  }),
  mermaidDialogCanvas: css({
    position: "relative",
    h: "100%",
    w: "100%",
  }),
  mermaidDialogPanZoom: css({
    position: "absolute",
    left: "50%",
    top: "50%",
    transformOrigin: "center center",
    willChange: "transform",
    "& svg": {
      display: "block",
      maxW: "none",
      h: "auto",
      pointerEvents: "none",
      userSelect: "none",
    },
  }),
};
